### ISSUE TITLE
Inherit preview.js parameters handlers in stories

### ISSUE THREAD

**Issue by sklawren** [mswjs/msw-storybook-addon#43] opened 2021-08-03 07:09 UTC
As per [Storybook rules of parameter inheritance](https://storybook.js.org/docs/react/writing-stories/parameters#rules-of-parameter-inheritance), using msw in stories should inherit/concat the handlers from the preview.js parameters.

Example:
The API I am using requires that I make a call for an oauth token before I can call any API call. In the current way this addon works, I have to duplicate this resolver in every single story that defines msw in its parameters because it overwrites the one from preview.js instead of merging with it.

**preview.js**
```javascript
export const parameters = {
    actions: {argTypesRegex: '^on[A-Z].*'},
    msw: [
        rest.post('/oauth/token', (req, res, ctx) =>
            res(ctx.json({token_type: 'Bearer', access_token: 'test_token'}))
        ),
    ],
};
```

**thing.stories.js**
```javascript
export default {
    component: Thing,
    parameters: {
        msw: [
            rest.get('/some/endpoint', (req, res, ctx) => 
                res(ctx.json([]))
            ),
        ],
    },
};
```

Both handlers should work in the story. Currently, the oauth/token handler is not included in the story.

**Comment by sklawren** [comment] 2021-08-03 09:36
This might be an issue internal to storybook with array parameters. I'll check with Shilman.

**Comment by shilman** [comment] 2021-08-03 10:06
Storybook parameter semantics are:
- Merge objects hierarchically
- Replace arrays

Given these constraints, if you wanted inheritance I'd consider changing the API to something like:

```js
  ...
  parameters: {
    msw: {
      token: rest.post('/oauth/token', (req, res, ctx) =>
        res(ctx.json({token_type: 'Bearer', access_token: 'test_token'}))
      ),
    }
  }
```

**Comment by sklawren** [comment] 2021-08-03 10:13
Got it! I'll submit a PR.

**Comment by kettanaito** [comment] 2021-08-03 15:56
Thanks for raising this, @sklawren. 

I wonder if we can implement the merge of lists internally in this add-on, would that be semantically appropriate for Storybook? We don't wish to introduce unexpected behaviors in regards to how users are used to Storybook handling story parameters. 

That being said, using a map to declare/manage request handlers is not the best option. Here are a few reasons why:

1. MSW users are accustomed to request handlers being declared and handled as a _list_ of handlers (functions). 
2. Request handlers are accumulative by design, not exclusive. The list is a data structure of choice for this characteristic. You can have multiple request handlers for the same endpoint and utilize their declaration order to enable more complex use cases.

If I understand correctly, the suggested data structure change will be handled by Storybook automatically:

```js
Story.parameters = {
  msw: {
    [handlersGroupName]: [...handlers]
  }
}
```

We should be able to get the initial handlers from `preview.js` and merge that list with any request handlers you assign to individual stories. I'd favor that approach.

**Comment by kettanaito** [comment] 2021-08-03 16:04
Hey, @shilman. Thank you for the insights into how Storybook handles the parameters. May I learn more about the decision to replace arrays instead of accumulating them? I'm pretty sure there were some use-cases I'm not aware of that led to that design decision.

**Comment by shilman** [comment] 2021-08-03 17:12
@kettanaito If you accumulate arrays then there's no natural way to override anything that's defined in a higher level in the hierarchy. The decision was made five years ago, so it's all a distant memory at this point. But my recollection is that initially we merged arrays and then we backed it out based on problems it caused.

**Comment by stevensacks** [comment] 2021-08-03 23:48
I don’t think that there’s any difference between using an array and using an object with named arrays. It’s an irrelevant distinction. The only difference is that one can’t be merged by storybook and the other can.
```js
{
  msw: {
    handlers: [one, two],
    // VS
    handlers: {
      0: one,
      1: two,
    },
    // VS
    handlers: {
      0: […foo, …bar],
      1: […baz],
    },
    // VS
    handlers: {
      groupA: […foo],
      other: […bar],
    }
  }
}
```
These are all functionally identical when you use a flattener like `Object.values(msw.handlers).filter(Boolean).reduce(concatFn)`

**Comment by shilman** [comment] 2021-08-04 01:51
@sklawren this is an interesting pattern. i wasn't a fan initially because "object merge with array flattening" is harder to explain than "object merge", but if one really wants to use arrays, this gets that AND merge AND backwards compatibility, which is pretty cool. A+ for creativity. my vote would still be for the simplicity of object merge, but i've got no horse in this race! 🏇

**Comment by stevensacks** [comment] 2021-08-04 03:13
MSW’s use() expects an array of handlers.

Storybook only merges objects.

With this PR, the addon seamlessly bridges the gap between MSW and Storybook.

The MSW “preferred practice” of using a composer function can still be used with this implementation. Or, you can opt for the “Storybook approach” of merging object parameters. Whether one is better than the other is open to opinion and differs based on the individual circumstances of the project.

Either way, both MSW and Storybook still get what they each expect.

**Comment by sklawren** [comment] 2021-09-07 02:24
It's been over a month since the last comment. Where do we stand on this?

**Comment by kettanaito** [comment] 2021-09-07 12:06
Maintainers of this repository were quite overwhelmed by personal and open-source work so it takes time to find a proper solution here. I'd gladly spend another month if it means deciding on the API that'd be comfortable for our users in the long run. Rushing is never an option.

At the moment, given more context over why object structure is beneficial, @yannbf and I have put down an incremental implementation plan that'd allow parameters merging. It will be developed in phases, ensuring backward compatibility. Please be patient while this is in progress.

Overall, I still find handlers-as-object redundant and unnecessarily verbose. It's de facto an escape hatch to enable Storybook internals to process parameters (merge in this case). I feel like asking our users to pay the price of aligning the MSW and Storybook internals isn't the right call.

## Data incongruence upon reusing the handlers

One more argument to this would be the difficulty we impose to reuse existing handlers in Storybook. We recommend writing handlers in a list (once again, object structure is a special snowflake for Storybook, there's no practical value or reason to store handlers as a `{name:handler}` structure). 

Consider a common MSW setup in an application:

```js
export const handlers = [
  rest.post('/login', loginResolver),
  rest.get('/user', userResolver)
]
```

Now if the user wishes to reuse their handlers in Storybook, which is the main value of MSW, they'd have to access specific handlers by index in order to assign them as global/meta/story parameters:

```js
import { handlers } from '../mocks/handlers'

MyStory.parameters = {
  msw: {
    handlers: {
      login: handlers[0],
      user: handlers[1]
    }
  }
}
```

Such reference is brittle and may easily lead to unexpected behaviors once you add/move/remove handlers. I wouldn't advise on restructuring handlers for Storybook alone, as it's still a rather specific use-case where MSW can be used.

Taking this into account, I'm currently considering having an internal mapping of the list of handlers to the object structure that supports parameter merging. Something along these lines:

```js
// msw-storybook-addon
function toObject(handlers) {
  return handlers.reduce((obj, handler) => {
    const name = `${handler.info.method}+${handler.info.mask}`
    obj[name] = handler
    return obj
  }, {})
}

msw(args) {
  // Accept "args.handlers" as a list of handlers
  // and map them to an object to support parameter merging.
  const obj = toObject(args.handlers)
}
```

My main motivation to considering such an approach is:

- Object structure is an internal requirement, not necessarily a public API change.
- Managing objects is still cumbersome, given 1 key represents 1 handler (the nested list of handlers has the same merge issues as the entire `handlers` property being a list).
- This makes the existing list of handlers immediately reusable with Storybook.

Such an approach also has some downsides, for instance, it becomes tedious to explicitly disable a certain handler for two reasons:

- The user has no access to the generated `name` of the handler in the object.
- The `handlers` property of the add-on is still a list, in this case, so they still cannot pass a value like `{ handleName: null }` to implement explicit disable of the handler.

Frankly, I see this downside as a rather relative one, and I'll elaborate on why that is below.

## Explicit vs Implicit

As I've stated previously, I'd always recommend our users favor explicit configurations. In this context, it implies composing the list of handlers for each Storybook configuration level (global/meta/story) individually:

```js
MyStory.parameters = {
  msw: {
    handlers: [
      ...auth,
      ...user
    ]
  }
}

AnotherStory.parameters = {
  msw: {
    handlers: [
      // I don't wish to have "auth" handlers here.
      ...user
    ]
  }
}
```

**The benefits of explicit configuration:**

- It's always easier to read because you don't need any external context to understand the applied values in their entirety.
- It's easy to add/remove values for specific use cases (stories).

In a general context, there are no downsides to explicit configuration. Usually, when people see such recommendations, they have one main concern: it's too verbose. I disagree with that statement. The benefits that explicit imports and usage give you outweigh any kind of verboseness by a mile. The cost of `import` is virtually zero (especially considering module concatenation during the build). The only reason to think this setup is verbose is when you assume a lot of handlers are being imported. That on its own is an issue, as I doubt you'll have more than 5-8 groups of handlers _at the same time_ for a story. If you do, I'd strongly recommend grouping your handlers by feature/domain—that'd be beneficial in general. You can also utilize functional composition as the last resort in the case of a justified large number of handlers.

In the context of this add-on, there's another downside to the explicit configuration: users' familiarity with parameter merging in Storybook. In no way do we wish to break the development flows the users of Storybook are accustomed to. At the same time, we wish to respect and support the development flows the users of MSW are accustomed to, so there are no "oh shoot" moments when integrating these tools. That's why I suggest combining the two experiences:

- Keep the handlers as a list for the users.
- Map the handlers to an object internally, so that parameter merging is functional as the users expect.

While the combination of these approaches has some difficulty on its own, I'd rather explore and solve that difficulty than ask our users to do an entirely different, unfamiliar setup when they switch to other tools.

**Closed** 2021-10-16 21:32 UTC
