### ISSUE TITLE
codesandbox for using the addon

### ISSUE THREAD

**Issue by chiptus** [mswjs/msw-storybook-addon#135] opened 2024-01-21 08:34 UTC
I found it hard to use the addon, I even thought of opening a bug and then when I created a sandbox I found my issue.

thought of posting the sandbox here as it shows a minimal config for msw and the addon:
https://codesandbox.io/p/devbox/react-storybook-msw-vmp5lp

**Comment by yannbf** [comment] 2024-05-16 12:56
Hey there, I'm glad you found the cause of your issue! Was the documentation of this addon not good? If so, you could provide a PR with improvements if possible.

I'll close it for cleanup sake, and also because the sandbox can get outdated over time (it already is). Thanks!

**Closed by yannbf** 2024-05-16 12:56 UTC
