### ISSUE TITLE
Webpack 5 Throws ModuleNotFoundError

### ISSUE THREAD

**Issue by KL13NT** [mswjs/msw-storybook-addon#47] opened 2021-08-23 21:38 UTC
Hi, I'm using Webpack^5.46.0, @storybook/react^6.3.4, msw-storybook-addon^1.2.0, and msw^0.35.0. I have Storybook configured to use Webpack 5. Whenever the Storybook dev server is running and I modify the preview to initialize the worker, it works. But when I shutdown the server and restart it, it breaks with the following error:

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it
```

This error is thrown multiple times for multiple packages. Has this been reported before? Any possible fix?

**Comment by KL13NT** [comment] 2021-08-23 21:57
Right now what I do to get this to not throw is remove the addon's decorator and initialize code from `preview.js`, wait for the dev-server to startup successfully, and then change `preview.js`. 

If I add the addon's initialize code before starting the server, it throws.

**Comment by mouhannad-sh** [comment] 2021-08-24 04:33
Went through the same thing just now...
following the error traces I tried the following and it worked for me (looking for a better solution :D )

I followed the setup guide from storybook to [support webpack 5](https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324)

my deps look like this now:
```json
"devDependencies": {
    "@storybook/addon-actions": "^6.4.0-alpha.11",
    "@storybook/addon-essentials": "^6.4.0-alpha.11",
    "@storybook/addon-links": "^6.4.0-alpha.11",
    "@storybook/builder-webpack5": "^6.4.0-alpha.11",
    "@storybook/manager-webpack5": "^6.4.0-alpha.11",
    "@storybook/react": "^6.4.0-alpha.11",
    "msw": "^0.35.0",
    "msw-storybook-addon": "^1.2.0"
},
"resolutions": {
    "webpack": "^5.45.1",
    "css-loader": "^5.0.0",
    "dotenv-webpack": "^6.0.0",
    "html-webpack-plugin": "^5.3.2",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^5.1.4",
    "webpack-dev-middleware": "^4.1.0",
    "webpack-virtual-modules": "^0.4.2",
  }
```
Then in `.storybook/main.js` I have a custom webpackFinal setup to modify SB's pollyfil configs 

```js
webpackFinal: config => {
    return {
      ...config,
      resolve: {
        ...config.resolve,
        modules: [path.resolve("./src"), ...config.resolve.modules],
        fallback: {
           timers: false,
           tty: false,
           os: false,
           http: false,
           https: false,
           zlib: false,
           util: false,
           ...config.resolve.fallback,
        }
      }
    };
  }
```
Nowadays setting up Storybook feels like performing surgery !

**Comment by KL13NT** [comment] 2021-08-28 07:36
Thanks @mouhannad-sh, this worked perfectly for me. I suppose mswjs depends on some Node modules even when using it in the browser which explains why Webpack's fallback defaults were needed previously.

**Comment by kettanaito** [comment] 2021-09-06 13:04
Is there any stack trace to these errors?

MSW mustn't use any Node.js modules in a browser. We have two separate builds for the browser and Node.js. Can somebody confirm that a clean Storybook setup with webpack 5 behaves properly without the polyfills but adding this add-on results in errors?

**Comment by sklawren** [comment] 2021-09-15 10:35
I just upgraded my project from gatsby 2 to 3, which switches to webpack 5.

I followed all the instructions in the storybook webpack 5 documentation, and Shilman helped me debug it and this error kept happening.

I noticed the `@mswjs` in the ModuleNotFoundError, commented out the msw initialization code in preview.js
```
//import {initialize, mswDecorator} from 'msw-storybook-addon';
//initialize();
//addDecorator(mswDecorator);
```
Storybook launched without issue.

I followed @mouhannad-sh instructions, uncommented the msw storybook code and everything works again.

Here is the stack trace (it repeats this error multiple times, so I only pasted the first occurance).

```
manager (webpack 5.52.1) compiled successfully in 13889 ms
99% done plugins webpack-hot-middlewarewebpack built preview 34cdf0e9d905502cac0d in 19490ms
ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in '/Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
	- install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "http": false }
    at /Users/steven/Development/project/node_modules/webpack/lib/Compilation.js:1773:28
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:814:13
    at eval (eval at create (/Users/steven/Development/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/Users/steven/Development/project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:676:25
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:885:8
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:1005:5
    at /Users/steven/Development/project/node_modules/neo-async/async.js:6883:13
    at /Users/steven/Development/project/node_modules/webpack/lib/NormalModuleFactory.js:988:45
    at finishWithoutResolve (/Users/steven/Development/project/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/steven/Development/project/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/steven/Development/project/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/steven/Development/project/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve 'http' in '/Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest'
  Parsed request is a module
  using description file: /Users/steven/Development/project/node_modules/@mswjs/interceptors/package.json (relative path: ./lib/interceptors/ClientRequest)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in /Users/steven/Development/project/src
        single file module
          using description file: /Users/steven/Development/project/package.json (relative path: ./src/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/src/http.cjs doesn't exist
        /Users/steven/Development/project/src/http doesn't exist
      /Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/node_modules doesn't exist or is not a directory
      /Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/interceptors/node_modules doesn't exist or is not a directory
      /Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/node_modules doesn't exist or is not a directory
      looking for modules in /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules
        single file module
          using description file: /Users/steven/Development/project/node_modules/@mswjs/interceptors/package.json (relative path: ./node_modules/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http.cjs doesn't exist
        /Users/steven/Development/project/node_modules/@mswjs/interceptors/node_modules/http doesn't exist
      /Users/steven/Development/project/node_modules/@mswjs/node_modules doesn't exist or is not a directory
      /Users/steven/Development/project/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/steven/Development/project/node_modules
        single file module
          using description file: /Users/steven/Development/project/package.json (relative path: ./node_modules/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/node_modules/http.cjs doesn't exist
        /Users/steven/Development/project/node_modules/http doesn't exist
      /Users/steven/Development/amex/node_modules doesn't exist or is not a directory
      /Users/steven/Development/node_modules doesn't exist or is not a directory
      /Users/steven/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/steven/Development/project/test
        single file module
          using description file: /Users/steven/Development/project/package.json (relative path: ./test/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.tsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.json doesn't exist
            .cjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/steven/Development/project/test/http.cjs doesn't exist
        /Users/steven/Development/project/test/http doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'http' in '/Users/steven/Development/project/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest'
```

**Comment by kettanaito** [comment] 2021-09-15 22:30
Based on the stack trace, the issue is caused by the client-side Storybook loading a Node.js version of MSW (`setupServer`). That latter rightfully relies on Node.js built-ins like `http` because it's designed to run in that environment. 

@yannbf, do you think this may be an issue we've introduced with the worker/server dual support recently?

**Comment by yannbf** [comment] 2021-09-16 20:58
> Based on the stack trace, the issue is caused by the client-side Storybook loading a Node.js version of MSW (`setupServer`). That latter rightfully relies on Node.js built-ins like `http` because it's designed to run in that environment.
> 
> @yannbf, do you think this may be an issue we've introduced with the worker/server dual support recently?

That seems like it! However I don't understand why it would happen if that code is supposed to be lazy loaded 🤔
I'd love to check about this issue, though I'm not sure how to reproduce it. Can anyone provide a minimal repro?

**Comment by donferi** [comment] 2021-09-29 18:40
Hi @yannbf by any chance do you have a minimal repro? I'm experiencing the same issue in a different non-storybook repo but I haven't been able to isolate the issue. For some reason the server code is getting bundled even if my require is behind a conditional 🤔

**Comment by yannbf** [comment] 2021-10-09 22:24
Hey @donferi the thing is that webpack can't really tell whether a code will run at runtime or not, so even if you are 100% sure the node code will not run on the browser, webpack will still try to process it. There's a long discussion about that [here](https://github.com/webpack/webpack/issues/8826) if you'd like to get more context about it!

**Comment by kettanaito** [comment] 2021-10-10 22:37
The issue should be fixed by #53.

**Closed by kettanaito** 2021-10-10 22:37 UTC

**Comment by chiptus** [comment] 2022-02-24 14:41
> The issue should be fixed by #53.

still get the same issue

**Comment by kettanaito** [comment] 2022-02-24 15:43
Please update to msw@latest.

**Comment by chiptus** [comment] 2022-02-24 16:04
my problem was with using the wrong `rest`

**Comment by ninjarogue** [comment] 2022-03-04 16:12
I'm having a similar issue (mode not found errors when running app on the browser) without storybook. I'm importing a type from 'msw/node', could this issue have something to do with that?

**Comment by kettanaito** [comment] 2022-03-08 13:29
Hi, @ninjarogue. I belive I've replied to you in another thread. You have the mistake of missing `setupWorker` and `setupServer` in the same module. Those functions are meant for different environments and you cannot import them in a single module. Please split them by modules as shown in [the examples](https://github.com/mswjs/examples/tree/master/examples/rest-react/src/mocks) and the issue will be gone.
